source "https://rubygems.org"
ruby "3.4.7"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "jekyll", "~> 4.4.1"
gem "webrick"
gem "kramdown-parser-gfm"
gem "jekyll-include-cache"

# Jekyll compiles no sass on this site - the sass CLI does, from package.json. See README.md.
group :jekyll_plugins do
  gem "jekyll-tidy"
  gem "jekyll-gtm", path: "../../ruby/jekyll-gtm"
  gem "jekyll-filters", path: "../../ruby/jekyll-filters"
  gem "jekyll-multi-sitemap", path: "../../ruby/jekyll-multi-sitemap"
  gem "jekyll-resource-tags", path: "../../ruby/jekyll-resource-tags"
  gem "jekyll-page-meta", path: "../../ruby/jekyll-page-meta"
  gem "jekyll-structured-data", path: "../../ruby/jekyll-structured-data"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions of the gem
# do not have a Java counterpart.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
