<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ConsoleTables" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Enrichers.Environment" />
    <PackageReference Include="Serilog.Enrichers.Thread" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Binacle.ViPaq.Testing\Binacle.ViPaq.Testing.csproj" />
    <ProjectReference Include="..\..\data\Binacle.ViPaq.Data\Binacle.ViPaq.Data.csproj" />
    <ProjectReference Include="..\..\..\shared\test\Binacle.Reporting\Binacle.Reporting.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Binacle.Geometry" />
    <Using Include="Binacle.ViPaq.Data" />
    <Using Include="Binacle.ViPaq.Testing" />
  </ItemGroup>

</Project>
