<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\test\Binacle.Benchmarking\Binacle.Benchmarking.csproj" />
    <ProjectReference Include="..\..\src\Binacle.Lib\Binacle.Lib.csproj" />
    <ProjectReference Include="..\..\test\Binacle.Lib.Testing\Binacle.Lib.Testing.csproj" />
    <ProjectReference Include="..\..\..\shared\data\Binacle.Data\Binacle.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Binacle.Packing" />
    <Using Include="Binacle.Data" />
    <Using Include="Binacle.Lib.Testing" />
    <Using Include="Binacle.Benchmarking" />
    <Using Include="BenchmarkDotNet.Attributes" />
  </ItemGroup>

</Project>
