<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <InternalsVisibleTo Include="Binacle.Net.ServiceModule.IntegrationTests"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\shared\src\Binacle.FluxResults\Binacle.FluxResults.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Binacle.FluxResults" />
    </ItemGroup>
</Project>
